"""tables for transcription persistence

Revision ID: aa98cff14c49
Revises: 672f7322cc5b
Create Date: 2025-08-04 07:00:59.245590+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa98cff14c49'
down_revision: Union[str, None] = '672f7322cc5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcription_analyses',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('key_topics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sentiment', sa.String(length=50), nullable=False),
    sa.Column('main_themes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('important_quotes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('technical_terms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcription_insights',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('key_insights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action_items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('opportunities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('concerns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('next_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcription_processings',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('transcription_id', sa.String(length=255), nullable=False),
    sa.Column('analysis_id', sa.String(length=255), nullable=True),
    sa.Column('insights_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['transcription_analyses.id'], ),
    sa.ForeignKeyConstraint(['insights_id'], ['transcription_insights.id'], ),
    sa.ForeignKeyConstraint(['transcription_id'], ['transcriptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transcription_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transcription_processings')
    op.drop_table('transcription_insights')
    op.drop_table('transcription_analyses')
    # ### end Alembic commands ###
