"""set cascade for transcription tables

Revision ID: 4d471ac36e94
Revises: aa98cff14c49
Create Date: 2025-08-05 22:46:45.392917+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d471ac36e94'
down_revision: Union[str, None] = 'aa98cff14c49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('messages_session_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('transcription_processings_transcription_id_fkey', 'transcription_processings', type_='foreignkey')
    op.create_foreign_key(None, 'transcription_processings', 'transcriptions', ['transcription_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('transcriptions_session_id_fkey', 'transcriptions', type_='foreignkey')
    op.create_foreign_key(None, 'transcriptions', 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transcriptions', type_='foreignkey')
    op.create_foreign_key('transcriptions_session_id_fkey', 'transcriptions', 'sessions', ['session_id'], ['id'])
    op.drop_constraint(None, 'transcription_processings', type_='foreignkey')
    op.create_foreign_key('transcription_processings_transcription_id_fkey', 'transcription_processings', 'transcriptions', ['transcription_id'], ['id'])
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_session_id_fkey', 'messages', 'sessions', ['session_id'], ['id'])
    # ### end Alembic commands ###
